title: Benjamin Shapiro
description: Portfolio
theme: minima

# Minima: custom header links
header_pages:
  - _pages/home.md
  - _pages/projects.md
  - _pages/publications.md
  - _pages/creative.md

include:
    - _pages

exclude: 
    - README.md