title: Benjamin Shapiro
description: Portfolio
theme: minima

# Minima: custom header links
header_pages:
  - _pages/home.md
  - _pages/geo.md
  - _pages/space.md
  - _pages/ai.md
  - _pages/finance.md
  - _pages/publications.md
  - _pages/creative.md

include:
    - _pages

exclude: 
    - README.md
